<?php
include('/var/www/html/cordovezapp/app/src/libraries/TaxesCalcR70Reliquidate.php');

use PHPUnit\Framework\TestCase;

class testParcialREliquidate extends TestCase
{
    private $init_data = Array(
        [order] => Array
        (
            [id_pedido] => 10,
            [nro_pedido] => 033-18,
            [regimen] => 70,
            [tipo_cambio_impuestosR10] => False,
            [tipo_cambio_almaceneraR70] => False,
            [flete_aduana] => 1243.7500,
            [seguro_aduana] => 223.9200,
            [otros] => 0.00,
            [incoterm] => 'FOB',
            [pais_origen] => 'ESPAÑA',
            [ciudad_origen] => 'VALENCIA',
            [fecha_arribo] => '2018-07-20',
            [fecha_salida_bodega_puerto] => '2018-06-25',
            [fecha_ingreso_almacenera] => '2018-06-21',
            [fecha_salida_almacenera] => False,
            [dias_libres] => 26,
            [comentarios] => False,
            [observaciones] => False,
            [nro_refrendo] => '028-2018-70-00431593',
            [last_update] => '2018-08-01 12:33:47',
            [date_create] => '2018-06-27 10:30:48',
            [id_user] => 16,
            [bg_isclosed] => 0,
            [bg_haveExpenses] => 1,
            [have_etiquetas_fiscales] => 0,
            [exoneracion_arancel] => 0.00,
            [bg_have_tasa_control] => 0,
            [bg_isliquidated] => 0,
            [fodinfa] => False,
            [fodinfa_pagado] => False,
            [ice_advalorem] => False,
            [ice_advalorem_pagado] => False,
            [ice_especifico] => False,
            [ice_especifico_pagado] => False,
            [iva] => False,
            [iva_pagado] => False,
            [arancel_especifico_pagar] => False,
            [arancel_especifico_pagar_pagado] => False,
            [fecha_liquidacion] => False,
            [nro_liquidacion] => False,
            [arancel_advalorem_pagar] => False,
            [arancel_advalorem_pagar_pagado] => False,
            [liquidacion_con_tasa] => 0,
            [base_arancel_advalorem] => 0.100,
            [base_arancel_especifico] => 0.250,
            [base_ice_especifico] => 7.220,
            [base_ice_advalorem] => 4.320,
            [porcentaje_ice_advalorem] => 0.750,
            [base_iva] => 0.120,
            [base_fodinfa] => 0.005,
            [base_etiquetas] => 0.130,
            [fecha_cierre] => False,
            [id_user_cierre] => False,
            [tipo_cambio_go] => 1.00,
            [gasto_origen] => 1050.000,
            [fecha_llegada_cliente] => False,
            ),
        
        [order_invoices] => Array
        (
            [0] => Array
            (
                [id_pedido_factura] => 9,
                [nro_pedido] => 033-18,
                [id_factura_proveedor] => '1-03885',
                [identificacion_proveedor] => 'ESA13008339',
                [fecha_emision] => '2018-05-04',
                [valor] => 43191.00,
                [moneda] => EUROS,
                [tipo_cambio] => 1.000000000000,
                [vencimiento_pago] => '2018-08-02',
                [fecha_pago] => False,
                [date_create] => '2018-06-27 10:33:26',
                [last_update] => '2018-06-27 15:33:52',
                [id_user] => 15,
                [bg_isclosed] => 0,
                [gasto_origen] => 1050.000,
                )
            
            ),
        
        [order_invoice_detail] => Array
        (
            [0] => Array
            (
                [detalle_pedido_factura] => 33,
                [id_pedido_factura] => 9,
                [cod_contable] => '00000000000000000008',
                [grado_alcoholico] => 13,
                [nro_cajas] => 850,
                [costo_caja] => 27.6000000000,
                [date_create] => '2018-07-03 14:14:22',
                [last_update] => False,
                [id_user] => 1,
                [product] => False,
                [nro_factura_informativa] => False,
                [cantidad_x_caja] => False,
                [cajas_importadas] => False,
                [unidades_importadas] => False,
                [unidades] => False,
                [costo_unidad] => False,
                [peso] => False,
                [capacidad_ml] => False,
                [fob] => False,
                [fob_percent] => False,
                [seguro_aduana] => False,
                [flete_aduana] => False,
                [seguro] => False,
                [flete] => False,
                [gasto_origen] => False,
                [cif] => False,
                [fecha_liquidacion] => False,
                [nro_pedido] => False,
                [id_parcial] => False,
                [otros] => False,
                [prorrateo_parcial] => False,
                [prorrateo_pedido] => False,
                [prorrateos_total] => False,
                [tasa_control] => False,
                [fodinfa] => False,
                [iva] => False,
                [iva_unidad] => False,
                [iva_total] => False,
                [ex_aduana] => False,
                [ex_aduana_unitario] => False,
                [exaduana_sin_etiquetas] => False,
                [exaduana_sin_tasa] => False,
                [base_advalorem] => False,
                [base_ice_epecifico] => False,
                [ice_especifico] => False,
                [ice_especifico_unitario] => False,
                [ice_advalorem] => False,
                [ice_advalorem_sin_tasa] => False,
                [ice_advalorem_sin_etiquetas] => False,
                [ice_advalorem_unitario] => False,
                [arancel_especifico] => False,
                [arancel_advalorem] => False,
                [arancel_especifico_unitario] => False,
                [arancel_advalorem_unitario] => False,
                [arancel_especifico_liberado] => False,
                [arancel_advalorem_liberado] => False,
                [arancel_especifico_pagar] => False,
                [arancel_advalorem_pagar] => False,
                [etiquetas_fiscales] => False,
                [ice_unitario] => False,
                [total_ice] => False,
                [ice_advalorem_pagado] => False,
                [ice_advalorem_diferencia] => False,
                [indirectos] => False,
                [costo_total] => False,
                [costo_caja_final] => False,
                [costo_botella] => False,
                [ex_aduana_antes] => False,
                ),
            
            [1] => Array
            (
                [detalle_pedido_factura] => 32,
                [id_pedido_factura] => 9,
                [cod_contable] => '01012093230201010750',
                [grado_alcoholico] => 14.5,
                [nro_cajas] => 550,
                [costo_caja] => 11.2200000000,
                [date_create] => '2018-07-03 14:12:38',
                [last_update] => '2018-07-03 19:15:08',
                [id_user] => 1,
                [product] => False,
                [nro_factura_informativa] => False,
                [cantidad_x_caja] => False,
                [cajas_importadas] => False,
                [unidades_importadas] => False,
                [unidades] => False,
                [costo_unidad] => False,
                [peso] => False,
                [capacidad_ml] => False,
                [fob] => False,
                [fob_percent] => False,
                [seguro_aduana] => False,
                [flete_aduana] => False,
                [seguro] => False,
                [flete] => False,
                [gasto_origen] => False,
                [cif] => False,
                [fecha_liquidacion] => False,
                [nro_pedido] => False,
                [id_parcial] => False,
                [otros] => False,
                [prorrateo_parcial] => False,
                [prorrateo_pedido] => False,
                [prorrateos_total] => False,
                [tasa_control] => False,
                [fodinfa] => False,
                [iva] => False,
                [iva_unidad] => False,
                [iva_total] => False,
                [ex_aduana] => False,
                [ex_aduana_unitario] => False,
                [exaduana_sin_etiquetas] => False,
                [exaduana_sin_tasa] => False,
                [base_advalorem] => False,
                [base_ice_epecifico] => False,
                [ice_especifico] => False,
                [ice_especifico_unitario] => False,
                [ice_advalorem] => False,
                [ice_advalorem_sin_tasa] => False,
                [ice_advalorem_sin_etiquetas] => False,
                [ice_advalorem_unitario] => False,
                [arancel_especifico] => False,
                [arancel_advalorem] => False,
                [arancel_especifico_unitario] => False,
                [arancel_advalorem_unitario] => False,
                [arancel_especifico_liberado] => False,
                [arancel_advalorem_liberado] => False,
                [arancel_especifico_pagar] => False,
                [arancel_advalorem_pagar] => False,
                [etiquetas_fiscales] => False,
                [ice_unitario] => False,
                [total_ice] => False,
                [ice_advalorem_pagado] => False,
                [ice_advalorem_diferencia] => False,
                [indirectos] => False,
                [costo_total] => False,
                [costo_caja_final] => False,
                [costo_botella] => False,
                [ex_aduana_antes] => False,
                ),
            
            [2] => Array
            (
                [detalle_pedido_factura] => 30,
                [id_pedido_factura] => 9,
                [cod_contable] => '01012093290101010750',
                [grado_alcoholico] => 14,
                [nro_cajas] => 300,
                [costo_caja] => 21.0000000000,
                [date_create] => '2018-07-03 14:11:16',
                [last_update] => '2018-07-03 19:15:30',
                [id_user] => 1,
                [product] => False,
                [nro_factura_informativa] => False,
                [cantidad_x_caja] => False,
                [cajas_importadas] => False,
                [unidades_importadas] => False,
                [unidades] => False,
                [costo_unidad] => False,
                [peso] => False,
                [capacidad_ml] => False,
                [fob] => False,
                [fob_percent] => False,
                [seguro_aduana] => False,
                [flete_aduana] => False,
                [seguro] => False,
                [flete] => False,
                [gasto_origen] => False,
                [cif] => False,
                [fecha_liquidacion] => False,
                [nro_pedido] => False,
                [id_parcial] => False,
                [otros] => False,
                [prorrateo_parcial] => False,
                [prorrateo_pedido] => False,
                [prorrateos_total] => False,
                [tasa_control] => False,
                [fodinfa] => False,
                [iva] => False,
                [iva_unidad] => False,
                [iva_total] => False,
                [ex_aduana] => False,
                [ex_aduana_unitario] => False,
                [exaduana_sin_etiquetas] => False,
                [exaduana_sin_tasa] => False,
                [base_advalorem] => False,
                [base_ice_epecifico] => False,
                [ice_especifico] => False,
                [ice_especifico_unitario] => False,
                [ice_advalorem] => False,
                [ice_advalorem_sin_tasa] => False,
                [ice_advalorem_sin_etiquetas] => False,
                [ice_advalorem_unitario] => False,
                [arancel_especifico] => False,
                [arancel_advalorem] => False,
                [arancel_especifico_unitario] => False,
                [arancel_advalorem_unitario] => False,
                [arancel_especifico_liberado] => False,
                [arancel_advalorem_liberado] => False,
                [arancel_especifico_pagar] => False,
                [arancel_advalorem_pagar] => False,
                [etiquetas_fiscales] => False,
                [ice_unitario] => False,
                [total_ice] => False,
                [ice_advalorem_pagado] => False,
                [ice_advalorem_diferencia] => False,
                [indirectos] => False,
                [costo_total] => False,
                [costo_caja_final] => False,
                [costo_botella] => False,
                [ex_aduana_antes] => False,
                ),
            
            [3] => Array
            (
                [detalle_pedido_factura] => 31,
                [id_pedido_factura] => 9,
                [cod_contable] => '01012093290301010750',
                [grado_alcoholico] => 14,
                [nro_cajas] => 550,
                [costo_caja] => 13.2000000000,
                [date_create] => '2018-07-03 14:11:32',
                [last_update] => '2018-07-03 19:15:54',
                [id_user] => 1,
                [product] => False,
                [nro_factura_informativa] => False,
                [cantidad_x_caja] => False,
                [cajas_importadas] => False,
                [unidades_importadas] => False,
                [unidades] => False,
                [costo_unidad] => False,
                [peso] => False,
                [capacidad_ml] => False,
                [fob] => False,
                [fob_percent] => False,
                [seguro_aduana] => False,
                [flete_aduana] => False,
                [seguro] => False,
                [flete] => False,
                [gasto_origen] => False,
                [cif] => False,
                [fecha_liquidacion] => False,
                [nro_pedido] => False,
                [id_parcial] => False,
                [otros] => False,
                [prorrateo_parcial] => False,
                [prorrateo_pedido] => False,
                [prorrateos_total] => False,
                [tasa_control] => False,
                [fodinfa] => False,
                [iva] => False,
                [iva_unidad] => False,
                [iva_total] => False,
                [ex_aduana] => False,
                [ex_aduana_unitario] => False,
                [exaduana_sin_etiquetas] => False,
                [exaduana_sin_tasa] => False,
                [base_advalorem] => False,
                [base_ice_epecifico] => False,
                [ice_especifico] => False,
                [ice_especifico_unitario] => False,
                [ice_advalorem] => False,
                [ice_advalorem_sin_tasa] => False,
                [ice_advalorem_sin_etiquetas] => False,
                [ice_advalorem_unitario] => False,
                [arancel_especifico] => False,
                [arancel_advalorem] => False,
                [arancel_especifico_unitario] => False,
                [arancel_advalorem_unitario] => False,
                [arancel_especifico_liberado] => False,
                [arancel_advalorem_liberado] => False,
                [arancel_especifico_pagar] => False,
                [arancel_advalorem_pagar] => False,
                [etiquetas_fiscales] => False,
                [ice_unitario] => False,
                [total_ice] => False,
                [ice_advalorem_pagado] => False,
                [ice_advalorem_diferencia] => False,
                [indirectos] => False,
                [costo_total] => False,
                [costo_caja_final] => False,
                [costo_botella] => False,
                [ex_aduana_antes] => False,
                )
            
            ),
        
        [products_base] => Array
        (
            [0] => Array
            (
                [id_producto] => 514,
                [cod_contable] => '00000000000000000008',
                [identificacion_proveedor] => ESA13008339,
                [cod_ice] => '000000000000000000000000000000000000022',
                [nombre] => 'VINO ESP. ALBALI TINTO GRAN RESERVA DE LA FAMILIA',
                [capacidad_ml] => 750,
                [cantidad_x_caja] => 6,
                [grado_alcoholico] => 13,
                [costo_caja] => 27.6000000000,
                [estado] => 1,
                [custodia_doble] => 0,
                [comentarios] => False,
                [date_create] => '2018-07-03 14:13:57',
                [last_update] => False,
                [id_user] => 1,
                [pais_origen] => False,
                [peso] => 0.000,
                [detalle_pedido_factura] => 33,
                )
            
            ),
        
        [init_expenses] => Array
        (
            [0] => Array
            (
                [id_gastos_nacionalizacion] => 167,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'AGENTE INICIAL DOCUMENTAL',
                [tipo] => INICIAL,
                [valor_provisionado] => 242.00,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 14:20:49',
                [last_update] => False,
                [id_user] => 1,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [1] => Array
            (
                [id_gastos_nacionalizacion] => 160,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'ALMACENAJE INICIAL',
                [tipo] => INICIAL,
                [valor_provisionado] => 317.76,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 13:59:14',
                [last_update] => False,
                [id_user] => 1,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [2] => Array
            (
                [id_gastos_nacionalizacion] => 168,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'CANDADO SATELITAL',
                [tipo] => INICIAL,
                [valor_provisionado] => 50.00,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 14:20:49',
                [last_update] => False,
                [id_user] => 1,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [3] => Array
            (
                [id_gastos_nacionalizacion] => 161,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'CUSTODIA ARMADA',
                [tipo] => INICIAL,
                [valor_provisionado] => 490.00,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 13:59:24',
                [last_update] => False,
                [id_user] => 1,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [4] => Array
            (
                [id_gastos_nacionalizacion] => 164,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'DESCARGA ALMAGRO',
                [tipo] => INICIAL,
                [valor_provisionado] => 55.00,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 14:20:26',
                [last_update] => False,
                [id_user] => 1,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [5] => Array
            (
                [id_gastos_nacionalizacion] => 169,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'FLETE',
                [tipo] => INICIAL,
                [valor_provisionado] => 1102.96,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 14:21:00',
                [last_update] => '2018-07-16 11:09:06',
                [id_user] => 16,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [6] => Array
            (
                [id_gastos_nacionalizacion] => 166,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'GASTOS LOCALES',
                [tipo] => INICIAL,
                [valor_provisionado] => 250.00,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 14:20:35',
                [last_update] => False,
                [id_user] => 1,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [7] => Array
            (
                [id_gastos_nacionalizacion] => 424,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'ISD',
                [tipo] => INICIAL,
                [valor_provisionado] => 2212.05,
                [comentarios] => False,
                [fecha] => '2018-08-02',
                [fecha_fin] => False,
                [date_create] => '2018-08-02 16:10:19',
                [last_update] => False,
                [id_user] => 1,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [8] => Array
            (
                [id_gastos_nacionalizacion] => 159,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'POLIZA SEGURO',
                [tipo] => INICIAL,
                [valor_provisionado] => 233.33,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 13:58:51',
                [last_update] => False,
                [id_user] => 1,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [9] => Array
            (
                [id_gastos_nacionalizacion] => 163,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'THC',
                [tipo] => INICIAL,
                [valor_provisionado] => 160.00,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 13:59:51',
                [last_update] => '2018-07-16 11:09:13',
                [id_user] => 16,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            [10] => Array
            (
                [id_gastos_nacionalizacion] => 165,
                [nro_pedido] => 033-18,
                [id_parcial] => 0,
                [identificacion_proveedor] => 0,
                [concepto] => 'TRANSPORTE INTERNO NORMALUIO-GYE',
                [tipo] => INICIAL,
                [valor_provisionado] => 660.00,
                [comentarios] => False,
                [fecha] => '2018-07-03',
                [fecha_fin] => False,
                [date_create] => '2018-07-03 14:20:26',
                [last_update] => False,
                [id_user] => 1,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                )
            
            ),
        
        [parcial] => Array
        (
            [id_parcial] => 4,
            [fecha_nacionalizacion] => False,
            [id_user] => 14,
            [bg_isclosed] => 1,
            [fecha_salida_almacenera] => False,
            [proximo_almacenaje_desde] => False,
            [nro_pedido] => 033-18,
            [date_create] => '2018-07-05 15:38:31',
            [tipo_cambio] => 1.1648000000,
            [last_update] => '2018-07-31 00:00:00',
            [bg_have_etiquetas_fiscales] => 0,
            [otros] => 0.000,
            [observaciones] => False,
            [bg_have_tasa_control] => 0,
            [exoneracion_arancel] => 100.00,
            [bg_isliquidated] => 1,
            [fodinfa] => 71.774,
            [fodinfa_pagado] => 71.774,
            [ice_advalorem] => 4623.384,
            [ice_advalorem_pagado] => 4623.384,
            [ice_especifico] => 1795.073,
            [ice_especifico_pagado] => 1795.073,
            [iva] => 2501.396,
            [iva_pagado] => 2501.396,
            [arancel_advalorem_pagar] => 0.000,
            [arancel_advalorem_pagar_pagado] => 0,
            [liquidacion_con_tasa] => 0,
            [base_arancel_advalorem] => 0.010,
            [base_arancel_especifico] => 0.250,
            [base_ice_especifico] => 7.220,
            [base_ice_advalorem] => 4.320,
            [porcentaje_ice_advalorem] => 0.750,
            [base_iva] => 0.120,
            [base_fodinfa] => 0.005,
            [base_etiquetas] => 0.130,
            [arancel_especifico_pagar] => 0.000,
            [arancel_especifico_pagar_pagado] => 0.000,
            [fecha_liquidacion] => '2018-06-27',
            [nro_liquidacion] => 37422517,
            [fecha_cierre] => '2018-08-09',
            [id_user_cierre] => 1,
            [fecha_llegada_cliente] => False,
            ),
        
        [all_parcials] => Array
        (
            [0] => Array
            (
                [id_parcial] => 4,
                [fecha_nacionalizacion] => False,
                [id_user] => 14,
                [bg_isclosed] => 1,
                [fecha_salida_almacenera] => False,
                [proximo_almacenaje_desde] => False,
                [nro_pedido] => 033-18,
                [date_create] => '2018-07-05 15:38:31',
                [tipo_cambio] => 1.1648000000,
                [last_update] => '2018-07-31 00:00:00',
                [bg_have_etiquetas_fiscales] => 0,
                [otros] => 0.000,
                [observaciones] => False,
                [bg_have_tasa_control] => 0,
                [exoneracion_arancel] => 100.00,
                [bg_isliquidated] => 1,
                [fodinfa] => 71.774,
                [fodinfa_pagado] => 71.774,
                [ice_advalorem] => 4623.384,
                [ice_advalorem_pagado] => 4623.384,
                [ice_especifico] => 1795.073,
                [ice_especifico_pagado] => 1795.073,
                [iva] => 2501.396,
                [iva_pagado] => 2501.396,
                [arancel_advalorem_pagar] => 0.000,
                [arancel_advalorem_pagar_pagado] => 0,
                [liquidacion_con_tasa] => 0,
                [base_arancel_advalorem] => 0.010,
                [base_arancel_especifico] => 0.250,
                [base_ice_especifico] => 7.220,
                [base_ice_advalorem] => 4.320,
                [porcentaje_ice_advalorem] => 0.750,
                [base_iva] => 0.120,
                [base_fodinfa] => 0.005,
                [base_etiquetas] => 0.130,
                [arancel_especifico_pagar] => 0.000,
                [arancel_especifico_pagar_pagado] => 0.000,
                [fecha_liquidacion] => '2018-06-27',
                [nro_liquidacion] => 37422517,
                [fecha_cierre] => '2018-08-09',
                [id_user_cierre] => 1,
                [fecha_llegada_cliente] => False,
                ),
            
            [1] => Array
            (
                [id_parcial] => 15,
                [fecha_nacionalizacion] => False,
                [id_user] => 16,
                [bg_isclosed] => 0,
                [fecha_salida_almacenera] => False,
                [proximo_almacenaje_desde] => False,
                [nro_pedido] => 033-18,
                [date_create] => '2018-07-24 15:52:34',
                [tipo_cambio] => 1.0000000000,
                [last_update] => False,
                [bg_have_etiquetas_fiscales] => 1,
                [otros] => 0.000,
                [observaciones] => False,
                [bg_have_tasa_control] => 0,
                [exoneracion_arancel] => 100.00,
                [bg_isliquidated] => 0,
                [fodinfa] => False,
                [fodinfa_pagado] => False,
                [ice_advalorem] => False,
                [ice_advalorem_pagado] => False,
                [ice_especifico] => False,
                [ice_especifico_pagado] => False,
                [iva] => False,
                [iva_pagado] => False,
                [arancel_advalorem_pagar] => False,
                [arancel_advalorem_pagar_pagado] => False,
                [liquidacion_con_tasa] => 0,
                [base_arancel_advalorem] => 0.100,
                [base_arancel_especifico] => 0.250,
                [base_ice_especifico] => 7.220,
                [base_ice_advalorem] => 4.320,
                [porcentaje_ice_advalorem] => 0.750,
                [base_iva] => 0.120,
                [base_fodinfa] => 0.005,
                [base_etiquetas] => 0.130,
                [arancel_especifico_pagar] => False,
                [arancel_especifico_pagar_pagado] => False,
                [fecha_liquidacion] => False,
                [nro_liquidacion] => False,
                [fecha_cierre] => False,
                [id_user_cierre] => False,
                [fecha_llegada_cliente] => False,
                )
            
            ),
        
        [parcial_expenses] => Array
        (
            [0] => Array
            (
                [id_gastos_nacionalizacion] => 172,
                [nro_pedido] => 000-00,
                [id_parcial] => 4,
                [identificacion_proveedor] => 0,
                [concepto] => 'ETIQUETAS FISCALES',
                [tipo] => NACIONALIZACION,
                [valor_provisionado] => 331.50,
                [comentarios] => False,
                [fecha] => '2018-07-05',
                [fecha_fin] => False,
                [date_create] => '2018-07-05 16:15:54',
                [last_update] => False,
                [id_user] => 14,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [1] => Array
            (
                [id_gastos_nacionalizacion] => 173,
                [nro_pedido] => 000-00,
                [id_parcial] => 4,
                [identificacion_proveedor] => 0,
                [concepto] => 'ETIQUETADO ESPACIO ALMAGRO',
                [tipo] => NACIONALIZACION,
                [valor_provisionado] => 6.84,
                [comentarios] => False,
                [fecha] => '2018-07-05',
                [fecha_fin] => False,
                [date_create] => '2018-07-05 16:15:54',
                [last_update] => '2018-07-19 15:07:12',
                [id_user] => 16,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [2] => Array
            (
                [id_gastos_nacionalizacion] => 174,
                [nro_pedido] => 000-00,
                [id_parcial] => 4,
                [identificacion_proveedor] => 0,
                [concepto] => 'AGENTE ADUANA',
                [tipo] => NACIONALIZACION,
                [valor_provisionado] => 198.00,
                [comentarios] => False,
                [fecha] => '2018-07-05',
                [fecha_fin] => False,
                [date_create] => '2018-07-05 16:15:54',
                [last_update] => False,
                [id_user] => 14,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [3] => Array
            (
                [id_gastos_nacionalizacion] => 273,
                [nro_pedido] => 000-00,
                [id_parcial] => 4,
                [identificacion_proveedor] => 0,
                [concepto] => 'DEPOSITO 2018Jun-2018Jul',
                [tipo] => NACIONALIZACION,
                [valor_provisionado] => 239.33,
                [comentarios] => False,
                [fecha] => '2018-06-21',
                [fecha_fin] => '2018-07-20',
                [date_create] => '2018-07-19 18:14:22',
                [last_update] => False,
                [id_user] => 14,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [4] => Array
            (
                [id_gastos_nacionalizacion] => 274,
                [nro_pedido] => 000-00,
                [id_parcial] => 4,
                [identificacion_proveedor] => 0,
                [concepto] => 'TRANSPORTE',
                [tipo] => NACIONALIZACION,
                [valor_provisionado] => 93.00,
                [comentarios] => False,
                [fecha] => '2018-07-20',
                [fecha_fin] => False,
                [date_create] => '2018-07-20 09:42:54',
                [last_update] => False,
                [id_user] => 4,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [5] => Array
            (
                [id_gastos_nacionalizacion] => 275,
                [nro_pedido] => 000-00,
                [id_parcial] => 4,
                [identificacion_proveedor] => 0,
                [concepto] => 'MANO DE OBRA ETIQUETADO',
                [tipo] => NACIONALIZACION,
                [valor_provisionado] => 76.50,
                [comentarios] => False,
                [fecha] => '2018-07-20',
                [fecha_fin] => False,
                [date_create] => '2018-07-20 09:42:54',
                [last_update] => False,
                [id_user] => 4,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                ),
            
            [6] => Array
            (
                [id_gastos_nacionalizacion] => 276,
                [nro_pedido] => 000-00,
                [id_parcial] => 4,
                [identificacion_proveedor] => 0,
                [concepto] => 'DESCARGA',
                [tipo] => NACIONALIZACION,
                [valor_provisionado] => 42.00,
                [comentarios] => False,
                [fecha] => '2018-07-20',
                [fecha_fin] => False,
                [date_create] => '2018-07-20 09:42:54',
                [last_update] => False,
                [id_user] => 4,
                [bg_closed] => 1,
                [bg_is_visible_gi] => 1,
                )
            
            ),
        
        [info_invoices] => Array
        (
            [0] => Array
            (
                [id_factura_informativa] => 4,
                [id_parcial] => 4,
                [nro_factura_informativa] => '2015384',
                [identificacion_proveedor] => '0990304262001',
                [fecha_emision] => '2018-06-27',
                [flete_aduana] => 256.64,
                [seguro_aduana] => 52.49,
                [valor] => 11730.00,
                [moneda] => EUROS,
                [nro_refrendo] => 055-'2018-10-00449082',
                [tipo_cambio] => 1.250000000000,
                [date_create] => '2018-07-05 15:40:37',
                [last_update] => '2018-07-19 18:07:08',
                [id_user] => 14,
                [comentarios] => False,
                [bg_isclosed] => 0,
                [gasto_origen] => 284.650,
                )
            
            ),
        
        [products] => Array
        (
            [0] => Array
            (
                [id_factura_informativa_detalle] => 9,
                [id_factura_informativa] => 4,
                [grado_alcoholico] => 13.000,
                [detalle_pedido_factura] => 33,
                [nro_cajas] => 425,
                [date_create] => '2018-07-05 15:51:54',
                [last_update] => '2018-07-19 18:07:27',
                [id_user] => 14,
                [product] => 'VINO ESP. ALBALI TINTO GRAN RESERVA DE LA FAMILIA',
                [cod_contable] => 0000000000,
                [nro_factura_informativa] => 2015384,
                [cantidad_x_caja] => 6.000,
                [cajas_importadas] => 850.000,
                [unidades_importadas] => 5100.000,
                [unidades] => 2550.000,
                [costo_caja] => 27.600,
                [costo_unidad] => 4.600,
                [peso] => 0.000,
                [capacidad_ml] => 750.000,
                [fob] => 13663.104,
                [fob_percent] => 1.000,
                [seguro_aduana] => 61.140,
                [flete_aduana] => 298.934,
                [seguro] => 0.000,
                [flete] => 0.000,
                [gasto_origen] => 331.560,
                [cif] => 14354.739,
                [fecha_liquidacion] => 2018.000,
                [nro_pedido] => 033-18,
                [id_parcial] => 4.000,
                [otros] => 0.000,
                [prorrateo_parcial] => 812.838,
                [prorrateo_pedido] => 1567.884,
                [prorrateos_total] => 2712.282,
                [tasa_control] => 0.000,
                [fodinfa] => 71.774,
                [iva] => 2501.396,
                [iva_unidad] => 0.981,
                [iva_total] => 2501.396,
                [ex_aduana] => 14758.013,
                [ex_aduana_unitario] => 5.787,
                [exaduana_sin_etiquetas] => 14426.513,
                [exaduana_sin_tasa] => 14426.513,
                [base_advalorem] => 3.240,
                [base_ice_epecifico] => 7.220,
                [ice_especifico] => 1795.073,
                [ice_especifico_unitario] => 0.704,
                [ice_advalorem] => 4872.010,
                [ice_advalorem_sin_tasa] => 4623.385,
                [ice_advalorem_sin_etiquetas] => 4623.385,
                [ice_advalorem_unitario] => 1.911,
                [arancel_especifico] => 0.000,
                [arancel_advalorem] => 0.000,
                [arancel_especifico_unitario] => 2.438,
                [arancel_advalorem_unitario] => 0.000,
                [arancel_especifico_liberado] => 6215.625,
                [arancel_advalorem_liberado] => 0.000,
                [arancel_especifico_pagar] => 0.000,
                [arancel_advalorem_pagar] => 0.000,
                [etiquetas_fiscales] => 331.500,
                [ice_unitario] => 1.911,
                [total_ice] => 6667.082,
                [ice_advalorem_pagado] => 4623.385,
                [ice_advalorem_diferencia] => 248.625,
                [indirectos] => 9451.138,
                [costo_total] => 23114.242,
                [costo_caja_final] => 54.386,
                [costo_botella] => 9.064,
                [ex_aduana_antes] => False,
                )
            
            ),
        
        [last_prorrateo] => False,
        
        [fobs_parcial] => Array
        (
            [fob_inicial] => 43191,
            [fob_saldo] => 43191,
            [fob_parcial] => 11730,
            [fob_parcial_razon_inicial] => 0.27158435785233,
            [fob_parcial_razon_saldo] => 0.27158435785233,
            [fob_proximo_parcial] => 31461,
            [prorrateo_seguro_aduana] => 52.49,
            [prorrateo_flete_aduana] => 256.64,
            ),
        
        [warenhouses] => Array
        (
            [almacenaje_parcial] => 239.33,
            [almacenaje_anterior] => 0,
            [almacenaje_total_parcial] => 239.33,
            [almacenaje_aplicado] => 64.998284364798,
            [almacenaje_proximo_parcial] => 174.3317156352,
            [detail] => Array
            (
                [0] => Array
                (
                    [id_gastos_nacionalizacion] => 273,
                    [nro_pedido] => 000-00,
                    [id_parcial] => 4,
                    [identificacion_proveedor] => 0,
                    [concepto] => 'DEPOSITO 2018Jun-2018Jul',
                    [tipo] => NACIONALIZACION,
                    [valor_provisionado] => 239.33,
                    [comentarios] => False,
                    [fecha] => '2018-06-21',
                    [fecha_fin] => '2018-07-20',
                    [date_create] => '2018-07-19 18:14:22',
                    [last_update] => False,
                    [id_user] => 14,
                    [bg_closed] => 1,
                    [bg_is_visible_gi] => 1,
                    )
                
                )
            
            )
        );
    
    private $parcial = [];
    private $prorrateo = [];
    private $param_taxes = [];
    private $taxes;
    
    
    /**
     * Creand el objeto con los datos inciales de la clase
     */
    public function __construct()
    {
        $this->taxes = new parcialTaxesReliquidate(
                $this->init_data, 
                $this->prorrateo, 
                $this->param_taxes, 
                $this->parcial
            );
    }
    
    
    public function testGetTaxes(){
        $this->assertArrayHasKey('sums', $this->taxes->getTaxes());
    }
   
}
